spring:
  application:
    name: BDGest-api
  datasource:
    url: jdbc:postgresql://postgres:5432/db_bd
    username: bd_root
    password: BD123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.connection.useUnicode: true
        hibernate.connection.characterEncoding: UTF-8
        hibernate.connection.charSet: UTF-8
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080